import { analyzeAssociationRepair, runAssociationRepair, analyzePersonaBackfill, runPersonaBackfill, analyzeNormalize, runNormalize } from './src/engine/stages/hygiene.js';
console.log('=== ASSOCIATION REPAIR ===');
console.log('candidates:', (await analyzeAssociationRepair()).candidates);
console.log(JSON.stringify(await runAssociationRepair(console.log)));
console.log('\n=== NORMALIZE ===');
console.log('candidates:', (await analyzeNormalize()).candidates);
console.log(JSON.stringify(await runNormalize(console.log)));
console.log('\n=== PERSONA BACKFILL ===');
console.log('candidates:', (await analyzePersonaBackfill()).candidates);
console.log(JSON.stringify(await runPersonaBackfill(console.log)));
process.exit(0);
